# Generated by Django 4.2.7 on 2025-06-23 09:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserSummaryState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(help_text="Slack user ID", max_length=50)),
                (
                    "channel_id",
                    models.CharField(help_text="Slack channel ID", max_length=50),
                ),
                (
                    "last_summary_ts",
                    models.CharField(
                        help_text="Slack timestamp of last summarized message",
                        max_length=20,
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserChannelReadState",
        ),
        migrations.AddIndex(
            model_name="usersummarystate",
            index=models.Index(
                fields=["user_id", "channel_id"], name="bot_usersum_user_id_cf0243_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="usersummarystate",
            index=models.Index(
                fields=["updated_at"], name="bot_usersum_updated_e484e3_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="usersummarystate",
            unique_together={("user_id", "channel_id")},
        ),
    ]
