# Generated by Django 4.2.7 on 2025-06-23 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_usersummarystate_delete_userchannelreadstate_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=50)),
                ("channel_id", models.CharField(max_length=50)),
                ("feedback", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
