# Generated by Django 4.2.7 on 2025-06-26 03:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=50)),
                ('channel_name', models.CharField(max_length=100)),
                ('added_by', models.CharField(max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ChannelCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Channel Categories',
            },
        ),
        migrations.CreateModel(
            name='FilterCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(choices=[('user', 'User'), ('keyword', 'Keyword'), ('reaction', 'Reaction'), ('time_range', 'Time Range'), ('has_thread', 'Has Thread'), ('has_files', 'Has Files')], max_length=20)),
                ('operator', models.CharField(choices=[('equals', 'Equals'), ('contains', 'Contains'), ('starts_with', 'Starts With'), ('ends_with', 'Ends With'), ('greater_than', 'Greater Than'), ('less_than', 'Less Than'), ('is_true', 'Is True'), ('is_false', 'Is False')], max_length=20)),
                ('value', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=50)),
                ('match_type', models.CharField(choices=[('all', 'Match All'), ('any', 'Match Any')], default='all', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='usersummarystate',
            name='bot_usersum_user_id_cf0243_idx',
        ),
        migrations.RemoveIndex(
            model_name='usersummarystate',
            name='bot_usersum_updated_e484e3_idx',
        ),
        migrations.RemoveField(
            model_name='usersummarystate',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='usersummarystate',
            name='channel_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersummarystate',
            name='last_summary_ts',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='usersummarystate',
            name='user_id',
            field=models.CharField(max_length=50),
        ),
        migrations.AddField(
            model_name='filtercondition',
            name='filter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='bot.messagefilter'),
        ),
        migrations.AddField(
            model_name='categorychannel',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channels', to='bot.channelcategory'),
        ),
        migrations.AlterUniqueTogether(
            name='categorychannel',
            unique_together={('category', 'channel_id')},
        ),
    ]
